name: web_renderer
description: Renders images with HTTP requests.
version: 0.0.5
repository: https://github.com/KaikyuLotus/flutter_web_renderer

environment:
  sdk: ">=3.13.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.2
  intl: ^0.20.3
  screenshot: ^3.0.0
  shelf: ^1.4.2
  synchronized: ^3.4.1+2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WebRendererPlugin
      macos:
        pluginClass: WebRendererPlugin
      windows:
        pluginClass: WebRendererPlugin
