name: web_renderer
description: Renders images with HTTP requests.
version: 0.0.5
repository: https://github.com/KaikyuLotus/flutter_web_renderer

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  intl: ^0.17.0
  screenshot: ^2.5.0
  shelf: ^1.4.1
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WebRendererPlugin
      macos:
        pluginClass: WebRendererPlugin
      windows:
        pluginClass: WebRendererPlugin
